%% Focused US06 reference-SOC anchor evidence
% Works from current, numeric time, the dataset's own Ah counter, the
% approved capacity, and the documented test protocol. Voltage only gets
% logged as a measurement condition; it's never used to infer or adjust SOC.

clearvars;

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'src'));

us06File = fullfile(projectRoot, 'data', 'raw', ...
    '03-20-17_01.43 25degC_US06_Pan18650PF.mat');
[data, loadReport] = loadDataset(string(us06File));
raw = load(us06File, 'meas');
params = ecmParams();

activeCurrentThresholdA = 0.05;
rawAh = raw.meas.Ah(data.sourceRow);
activePositions = find(abs(data.I) > activeCurrentThresholdA);
assert(~isempty(activePositions), 'US06 must contain active-current samples.');

firstActivePosition = activePositions(1);
lastActivePosition = activePositions(end);
firstActiveSourceRow = data.sourceRow(firstActivePosition);
lastActiveSourceRow = data.sourceRow(lastActivePosition);

% Same right-endpoint convention as the approved C/20 evidence: I(k)
% applies over t(k)-t(k-1). The very first sample in this split file has
% no preceding interval to integrate over, so it just doesn't contribute one.
dt = diff(data.t);
integratedNetDischargeAh = sum(data.I(2:end) .* dt) / 3600;
datasetNetDischargeAh = -(rawAh(end) - rawAh(1));
throughputDifferenceAh = integratedNetDischargeAh - datasetNetDischargeAh;
throughputDifferencePercent = ...
    100 * throughputDifferenceAh / datasetNetDischargeAh;

candidateInitialSOC = 1;
candidateFinalSOCFromCurrent = ...
    candidateInitialSOC - integratedNetDischargeAh / params.Q_Ah;
candidateFinalSOCFromAh = ...
    candidateInitialSOC - datasetNetDischargeAh / params.Q_Ah;

assert(all(dt > 0), 'Loaded US06 numeric time must be strictly increasing.');
assert(isequal(loadReport.removedDuplicateSourceRows, 48061), ...
    'Expected exact duplicate source row 48061 to be removed.');
assert(firstActiveSourceRow == 3, ...
    'Expected first active US06 source row 3 at the stated threshold.');
assert(data.I(1) ~= 0 || data.I(2) ~= 0, ...
    'The initial samples unexpectedly form an exact zero-current rest.');
assert(candidateFinalSOCFromCurrent >= 0 && candidateFinalSOCFromCurrent <= 1, ...
    'Candidate final SOC must remain in the physical interval [0, 1].');
assert(abs(throughputDifferencePercent) < 0.01, ...
    'Current integration and dataset Ah differ by at least 0.01 percent.');

% Check how much that final exact-duplicate row actually matters if kept.
rawNormalisedCurrent = -raw.meas.Current(:);
rawIntegratedNetDischargeAh = ...
    sum(rawNormalisedCurrent(2:end) .* diff(raw.meas.Time(:))) / 3600;
duplicateIntegralEffectAh = ...
    rawIntegratedNetDischargeAh - integratedNetDischargeAh;
duplicateAhCounterEffectAh = raw.meas.Ah(48061) - raw.meas.Ah(48060);
assert(raw.meas.Time(48061) == raw.meas.Time(48060), ...
    'Expected zero dt across exact duplicate source rows 48060-48061.');
assert(duplicateIntegralEffectAh == 0, ...
    'Exact duplicate row 48061 must have zero current-integral effect.');
assert(duplicateAhCounterEffectAh == 0, ...
    'Exact duplicate row 48061 must have zero Ah-counter effect.');

initialBelowThresholdDurationS = ...
    data.t(firstActivePosition - 1) - data.t(1);
finalBelowThresholdDurationS = data.t(end) - data.t(lastActivePosition);

fprintf('\nUS06 initial and final measurement conditions\n');
fprintf(['  Initial source row %d: TimeStamp %s, t = %.9f s, I = %.6f A ' ...
    '(project sign), V = %.6f V, Ah = %.6f Ah, battery T = %.6f degC, ' ...
    'chamber T = %.6f degC.\n'], ...
    data.sourceRow(1), string(raw.meas.TimeStamp{data.sourceRow(1)}), ...
    data.t(1), data.I(1), data.V(1), rawAh(1), data.T(1), ...
    raw.meas.Chamber_Temp_degC(data.sourceRow(1)));
fprintf(['  Final retained source row %d: TimeStamp %s, t = %.9f s, ' ...
    'I = %.6f A, V = %.6f V, Ah = %.6f Ah, battery T = %.6f degC, ' ...
    'chamber T = %.6f degC.\n'], ...
    data.sourceRow(end), string(raw.meas.TimeStamp{data.sourceRow(end)}), ...
    data.t(end), data.I(end), data.V(end), rawAh(end), data.T(end), ...
    raw.meas.Chamber_Temp_degC(data.sourceRow(end)));
fprintf('  Voltage is reported only as context and is not used to tune SOC.\n');

fprintf('\nInitial-rest and active-row evidence\n');
fprintf(['  No directly observed initial zero-current rest exists: source ' ...
    'rows 1 and 2 have I = %.6f A and %.6f A.\n'], data.I(1), data.I(2));
fprintf(['  With |I| > %.3f A defining active current, the first active ' ...
    'source row is %d at t = %.9f s with I = %.6f A.\n'], ...
    activeCurrentThresholdA, firstActiveSourceRow, ...
    data.t(firstActivePosition), data.I(firstActivePosition));
fprintf(['  The pre-active below-threshold interval visible in this split ' ...
    'file is only %.9f s and is not classified as a rest anchor.\n'], ...
    initialBelowThresholdDurationS);
fprintf(['  The last active source row is %d; the retained record then has ' ...
    '%.9f s below the active threshold through source row %d.\n'], ...
    lastActiveSourceRow, finalBelowThresholdDurationS, data.sourceRow(end));

fprintf('\nActual-time current integration and Ah comparison\n');
fprintf(['  Convention: right endpoint, sum(I(k)*(t(k)-t(k-1)))/3600, ' ...
    'using every retained nonuniform numeric interval.\n']);
fprintf('  Integrated net discharge: %.12f Ah.\n', integratedNetDischargeAh);
fprintf('  Dataset Ah net discharge: %.12f Ah.\n', datasetNetDischargeAh);
fprintf('  Difference: %+.12f Ah (%+.9f%%).\n', ...
    throughputDifferenceAh, throughputDifferencePercent);

fprintf('\nEffect of exact duplicate source row 48061\n');
fprintf(['  loadDataset retains source row 48060 and removes source row 48061. ' ...
    'Both have t = %.9f s, raw current = %.6f A, and Ah = %.6f Ah.\n'], ...
    raw.meas.Time(48060), raw.meas.Current(48060), raw.meas.Ah(48060));
fprintf('  Effect on integrated throughput: %+.12f Ah.\n', ...
    duplicateIntegralEffectAh);
fprintf('  Effect on dataset Ah change: %+.12f Ah.\n', ...
    duplicateAhCounterEffectAh);

fprintf('\nReference-SOC anchor proposal (evidence only)\n');
fprintf(['  Candidate SOC_ref(1) = 1. The dataset protocol states that the ' ...
    'cell was charged after tests and identifies US06 within that charged ' ...
    'drive-cycle sequence. This is a protocol-supported full-charge ' ...
    'assumption, not a directly observed rested-OCV anchor in the split file.\n']);
fprintf(['  The split US06 file begins without a zero-current rest, so the ' ...
    'initial anchor retains protocol uncertainty and must not be justified ' ...
    'from terminal voltage or the fitted OCV model.\n']);
fprintf(['  Candidate final SOC from clean-current integration and approved ' ...
    'Q_Ah = %.9f Ah: %.12f.\n'], ...
    params.Q_Ah, candidateFinalSOCFromCurrent);
fprintf('  Corroborating final SOC from dataset Ah change: %.12f.\n', ...
    candidateFinalSOCFromAh);
fprintf(['  Recommendation: SOC_ref(1) = 1 is defensible as an explicit ' ...
    'protocol-supported working anchor, but not as a directly observed ' ...
    'rested anchor. Use %.12f as the corresponding current-integrated ' ...
    'candidate final SOC once the initial assumption is accepted.\n'], ...
    candidateFinalSOCFromCurrent);

fprintf(['\nNo voltage/OCV-based SOC adjustment and no production reference-SOC, ' ...
    'ECM, or estimator function was created.\n']);
