function buildModel()
%BUILDMODEL Programmatically construct simulink/ecm_ekf.slx.
%
%   Confirmed working: built and run end to end in MATLAB/Simulink on
%   2026-09-18. Block path strings and the Stateflow.EMChart mechanism for
%   writing a MATLAB Function block's code programmatically vary slightly
%   across MATLAB releases, so on a different version some add_block /
%   set_param calls may need adjusting.
%
%   SCOPE DECISION (see docs/DECISIONS.md, "Simulink model scope"): this
%   model doesn't rebuild src/ecmSimulate.m out of separate Discrete-Time
%   Integrator / 1-D Lookup Table / Discrete Transfer Fcn blocks. That
%   would just re-express math already implemented in MATLAB
%   (ecmSimulate.m, ekfEstimate.m) as an equivalent block diagram - more
%   surface area, same result, the kind of bloat this project has been
%   trying to avoid. Instead this model wraps the approved
%   src/ekfEstimate.m step logic in ONE MATLAB Function block, fed by From
%   Workspace inputs built from the same US06 record and OCV model as
%   experiments/expA_nominal.m. runSimulinkValidation.m then checks the
%   SOC output matches src/ekfEstimate.m to numerical precision. That
%   satisfies the actual requirement (an estimator running inside
%   Simulink, validated against the MATLAB reference) without building
%   more than this project can explain.
%
%   To adapt this to Experiments B-E instead of A: edit the hardcoded
%   SOC0/params/tuning constants inside the "EKF Step" MATLAB Function
%   block below to match the corresponding experiments/exp*.m script. The
%   block structure and validation script stay the same.

modelName = 'ecm_ekf';

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
new_system(modelName);
open_system(modelName);

%% From Workspace input blocks
% Base-workspace variables dt_ws, I_ws, V_ws must be [time, value]
% two-column matrices with identical time vectors, built by
% runSimulinkValidation.m before sim(modelName) runs. dt_ws(k,2) is
% t(k)-t(k-1) (0 for k=1), matching ekfEstimate.m's dt_k exactly. That
% means this block never has to rely on Simulink's own idea of elapsed
% time, just the sample values it's handed - which is why it lines up
% with ekfEstimate.m's for-loop over k=2:N.
%
% CORRECTION (2026-09-18): the first version of this used the real,
% nonuniform US06 time (seconds) as the From Workspace time base, with
% SampleTime -1 and a variable-step discrete solver, trying to get
% Simulink to step at each real sample time. Didn't work - Simulink fell
% back to an automatic ~50-step heuristic (MaxStep 'auto' doesn't really
% mean anything for a variable-step discrete solver with no explicit
% registered sample hits) and only logged 51 of 48060 samples. Fix:
% separate "which tick Simulink is on" from "how much real time that
% tick represents". The From Workspace time base below is now just the
% sample index (0, 1, 2, ... N-1, one integer tick per row), paired with
% a fixed-step discrete solver at FixedStep=1, so Simulink takes exactly
% N steps, one per row. The real elapsed time (dt) still goes into "EKF
% Step" as an explicit data value like before; Simulink's clock now only
% counts samples, not seconds.
add_block('simulink/Sources/From Workspace', [modelName '/dt']);
set_param([modelName '/dt'], 'VariableName', 'dt_ws', ...
    'SampleTime', '1', 'Interpolate', 'on', 'ZeroCross', 'off');

add_block('simulink/Sources/From Workspace', [modelName '/I']);
set_param([modelName '/I'], 'VariableName', 'I_ws', ...
    'SampleTime', '1', 'Interpolate', 'on', 'ZeroCross', 'off');

add_block('simulink/Sources/From Workspace', [modelName '/Vmeas']);
set_param([modelName '/Vmeas'], 'VariableName', 'V_ws', ...
    'SampleTime', '1', 'Interpolate', 'on', 'ZeroCross', 'off');

%% OCV polynomial coefficients as Constant blocks (from src/buildOCV.m's
%  degree-9 fit, passed as plain vectors rather than function handles
%  since MATLAB Function blocks compile to code and can't carry closures)
add_block('simulink/Sources/Constant', [modelName '/ocvCoeffs']);
set_param([modelName '/ocvCoeffs'], 'Value', 'ocvCoeffs_ws');

add_block('simulink/Sources/Constant', [modelName '/docvCoeffs']);
set_param([modelName '/docvCoeffs'], 'Value', 'docvCoeffs_ws');

%% MATLAB Function block: one EKF predict+update step per sample -
%  same math as one k-iteration of src/ekfEstimate.m's loop
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [modelName '/EKF Step']);

ekfStepCode = [ ...
    "function [SOC, V1, P_SOC] = ekfStep(dt, I, V_meas, ocvCoeffs, docvCoeffs)", ...
    "%#codegen", ...
    "% One predict+update step. Persistent state holds [SOC;V1] and P", ...
    "% between calls, mirroring the running x/P in ekfEstimate.m's", ...
    "% for-loop. dt==0 on the first call (see runSimulinkValidation.m,", ...
    "% dt_ws(1,2)=0) is the init trigger - same as ekfEstimate.m's k=1", ...
    "% special case, no predict/update on that first sample.", ...
    "", ...
    "persistent x P;", ...
    "", ...
    "% Hardcoded to match experiments/expA_nominal.m.", ...
    "% For Experiments B-E, change SOC0/R0/R1/tau/Q_As/tuning here to", ...
    "% match that experiment's script - nothing else needs to change.", ...
    "SOC0  = 1.0;", ...
    "R0    = 0.0312244650416;", ...
    "R1    = 0.0113287933401;", ...
    "tau   = 5.23962539484;", ...
    "Q_As  = 2.997393193 * 3600;", ...
    "P0_SOC = (0.01)^2; P0_V1 = (0.01)^2;", ...
    "q_SOC  = 1e-10;    q_V1  = 1e-6;", ...
    "R_V    = (3e-3)^2;", ...
    "", ...
    "if isempty(x)", ...
    "    x = [SOC0; 0];", ...
    "    P = diag([P0_SOC, P0_V1]);", ...
    "end", ...
    "", ...
    "if dt > 0", ...
    "    alpha = exp(-dt / tau);", ...
    "    x_pred = [x(1) - (dt / Q_As) * I; ...", ...
    "        alpha * x(2) + (1 - alpha) * R1 * I];", ...
    "    F = [1, 0; 0, alpha];", ...
    "    Qk = diag([q_SOC, q_V1]);", ...
    "    P_pred = F * P * F.' + Qk;", ...
    "", ...
    "    ocv_V = polyval(ocvCoeffs, x_pred(1));", ...
    "    docv_V = polyval(docvCoeffs, x_pred(1));", ...
    "    y_pred = ocv_V - x_pred(2) - R0 * I;", ...
    "    resid = V_meas - y_pred;", ...
    "", ...
    "    H = [docv_V, -1];", ...
    "    S = H * P_pred * H.' + R_V;", ...
    "    K = (P_pred * H.') / S;", ...
    "", ...
    "    x_upd = x_pred + K * resid;", ...
    "    P_upd = (eye(2) - K * H) * P_pred;", ...
    "    x_upd(1) = min(max(x_upd(1), 0), 1);", ...
    "", ...
    "    x = x_upd;", ...
    "    P = P_upd;", ...
    "end", ...
    "", ...
    "SOC = x(1);", ...
    "V1 = x(2);", ...
    "P_SOC = P(1, 1);", ...
    "end" ...
    ];

rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', [modelName '/EKF Step']);
chart.Script = strjoin(ekfStepCode, newline);

%% To Workspace logging blocks
add_block('simulink/Sinks/To Workspace', [modelName '/SOC_out']);
set_param([modelName '/SOC_out'], 'VariableName', 'SOC_simulink', ...
    'SaveFormat', 'Array');

add_block('simulink/Sinks/To Workspace', [modelName '/V1_out']);
set_param([modelName '/V1_out'], 'VariableName', 'V1_simulink', ...
    'SaveFormat', 'Array');

add_block('simulink/Sinks/To Workspace', [modelName '/PSOC_out']);
set_param([modelName '/PSOC_out'], 'VariableName', 'PSOC_simulink', ...
    'SaveFormat', 'Array');

%% Wiring
% Fixed-step discrete solver, FixedStep = 1 "tick" per sample. Paired
% with the From Workspace blocks above using sample index (not seconds)
% as their time base, this guarantees exactly N simulation steps for N
% data rows. See the correction note above for why the earlier
% variable-step, real-time-seconds approach silently under-sampled.
set_param(modelName, 'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', 'FixedStep', '1');

add_line(modelName, 'dt/1', 'EKF Step/1', 'autorouting', 'on');
add_line(modelName, 'I/1', 'EKF Step/2', 'autorouting', 'on');
add_line(modelName, 'Vmeas/1', 'EKF Step/3', 'autorouting', 'on');
add_line(modelName, 'ocvCoeffs/1', 'EKF Step/4', 'autorouting', 'on');
add_line(modelName, 'docvCoeffs/1', 'EKF Step/5', 'autorouting', 'on');
add_line(modelName, 'EKF Step/1', 'SOC_out/1', 'autorouting', 'on');
add_line(modelName, 'EKF Step/2', 'V1_out/1', 'autorouting', 'on');
add_line(modelName, 'EKF Step/3', 'PSOC_out/1', 'autorouting', 'on');

save_system(modelName, fullfile(fileparts(mfilename('fullpath')), 'ecm_ekf.slx'));
fprintf('Saved simulink/ecm_ekf.slx. Now run simulink/runSimulinkValidation.m.\n');
end
